---
# tasks file for roles/common

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  become: true

- name: Install common packages
  ansible.builtin.apt:
    name:
      - acl
    state: present
  become: true
